--- 
- name: Provision Ec2 instance and install packages 
  hosts: localhost
  gather_facts: no

  roles:
    - ec2_launch

- name: Configuration of Ec2 instance
  hosts: launched_ec2_instances
  gather_facts: yes
  roles:
    - common
    - docker 
    # - frontend
    # - backend


