---
# tasks file for backend
- name: Install backend dependencies 
  become: yes
  npm:
    path: /opt/todo-app/todo-backend
    state: present

- name: Install PM2
  become: yes
  npm:
    name: pm2
    global: yes

- name: Check if start.js exist
  stat: 
    path: /opt/todo-app/todo-backend/start.js
  register: start_js

- name: Debugging start.js existence
  debug:
    msg: "Start.js status: {{ start_js.stat.exists }}"

- name: Check the pm2 list
  become: yes
  command: pm2 list
  register: pm2_list
  changed_when: false

- name: Debug the pm2_list
  debug:
    var: pm2_list.how_lines

- name: Start or restart the backend with pm2 # you might have to remove this step later
  become: yes
  command: "/usr/bin/pm2 start -f start.js" #might have to remove the -f 
  args:
    chdir: /opt/todo-app/todo-backend 
  when: start_js.stat.exists

- name: Set pm2 to restart on Boot
  become: yes
  command: pm2 startup
  args:
    chdir: /opt/todo-app/todo-backend

    #new